### ISSUE TITLE
Get-LocalGroupMember returns "server could not be contacted"

### ISSUE THREAD

**Issue by zenchicken** [iSazonov/LocalAccounts-MS#1]
![image](https://github.com/user-attachments/assets/523711a9-d65c-4675-967d-769ea28825d1)

What other information can I obtain to help track this down?

**Comment by iSazonov** [comment]
`Get-Error` show more information about last error.

**Comment by zenchicken** [comment]
This system has local accounts in the Administrators group and one AzureAD principal. 

Output of `Get-ComputerInfo | Select-Object WindowsCurrentVersion,WindowsEdition,WindowsInstallationType,WindowsBuildLabEx | Format-List`

```
WindowsCurrentVersion   : 6.3
WindowsEdition          :
WindowsInstallationType : Client
WindowsBuildLabEx       : 22621.1.amd64fre.ni_release.220506-1250
```
Output of `Get-Error`
```Exception             :
    Type           : System.DirectoryServices.AccountManagement.PrincipalServerDownException
    TargetSite     :
        Name          : ReadServerConfig
        DeclaringType : [System.DirectoryServices.AccountManagement.PrincipalContext]
        MemberType    : Method
        Module        : System.DirectoryServices.AccountManagement.dll
    Message        : The server could not be contacted.
    InnerException :
        Type       : System.DirectoryServices.Protocols.LdapException
        ErrorCode  : 81
        TargetSite :
            Name          : Connect
            DeclaringType : [System.DirectoryServices.Protocols.LdapConnection]
            MemberType    : Method
            Module        : System.DirectoryServices.Protocols.dll
        Message    : The LDAP server is unavailable.
        Source     : System.DirectoryServices.Protocols
        HResult    : -2146233088
        StackTrace :
   at System.DirectoryServices.Protocols.LdapConnection.Connect()
   at System.DirectoryServices.Protocols.LdapConnection.SendRequestHelper(DirectoryRequest request, Int32& messageID)
   at System.DirectoryServices.Protocols.LdapConnection.SendRequest(DirectoryRequest request, TimeSpan requestTimeout)
   at System.DirectoryServices.AccountManagement.PrincipalContext.ReadServerConfig(String serverName,
ServerProperties& properties)
    Source         : System.DirectoryServices.AccountManagement
    HResult        : -2146233087
    StackTrace     :
   at System.DirectoryServices.AccountManagement.PrincipalContext.ReadServerConfig(String serverName,
ServerProperties& properties)
   at System.DirectoryServices.AccountManagement.PrincipalContext.DoServerVerifyAndPropRetrieval()
   at System.DirectoryServices.AccountManagement.PrincipalContext..ctor(ContextType contextType, String name, String
container, ContextOptions options, String userName, String password)
   at System.DirectoryServices.AccountManagement.PrincipalContext..ctor(ContextType contextType, String name)
   at LocalAccounts.Commands.BaseLocalGroupMemberCommand..ctor()
   at lambda_method206(Closure)
   at System.Management.Automation.CommandProcessor.ConstructInstance(Type type)
   at System.Management.Automation.CommandProcessor.Init(CmdletInfo cmdletInformation)
CategoryInfo          : NotSpecified: (:) [], PrincipalServerDownException
FullyQualifiedErrorId : System.DirectoryServices.AccountManagement.PrincipalServerDownException
InvocationInfo        :
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 4
    Line             : Get-LocalGroupMember -Group "Administrators"
    Statement        : Get-LocalGroupMember
    PositionMessage  : At line:1 char:1
                       + Get-LocalGroupMember -Group "Administrators"
                       + ~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Get-LocalGroupMember
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

**Comment by iSazonov** [comment]
@zenchicken Thanks! Is your computer not a member of a domain (and etc.)?

**Comment by iSazonov** [comment]
Do you see the error _only_ with Administrators group where Azure account present? No error with another group where only local accounts present?

Do you have access to Azure by 389 and 88 ports in the test time?

Do you see an error with Windows PowerShell? Does the output contains name and SID for the Azure account?

**Comment by iSazonov** [comment]
I can reproduce the error: disconnect ethernet cable before run Get-LocalGroupMember.

@zenchicken I think no Internet connection causes the error on your computer.

**Comment by zenchicken** [comment]
@iSazonov a few more bits of info.

The workstation I first reproduced this error does have a working Internet connection (I used it to post the GitHub issue). I am also able to reproduce the issue on a Windows 365 Desktop in Azure.

While I'm pretty sure there isn't any network blocking for Entra ID FQDNs and ports, I can validate specific ones. Do you know which FQDNs or IP ranges should be confirmed for `389/tcp` and `88/tcp`?

When testing another group (Users), the command fails in the same way on the Windows 365 Desktop and on the original local desktop.   What is interesting here:
- the Windows 365 Desktop Users group only has two built-in members: `NT Authority\Authenticated Users` and `NT Authority\Interactive`
- The original desktop I reported using does not have any AzureAD/Entra accounts in its Users Group 

As for the Windows PowerShell 5.x attempt; I get the dreaded:
```
PS $> Get-LocalGroupMember -Group Administrators
Get-LocalGroupMember : Failed to compare two elements in the array.
At line:1 char:1
+ Get-LocalGroupMember -Group Administrators
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-LocalGroupMember], InvalidOperationException
    + FullyQualifiedErrorId : An unspecified error occurred.,Microsoft.PowerShell.Commands.GetLocalGroupMemberCommand
```

What other info can I provide?

**Comment by iSazonov** [comment]
@zenchicken Thanks for additional information!

> Get-LocalGroupMember : Failed to compare two elements in the array.

In Windows PowerShell this says that it can not resolve user name by its SID.
In other words, Windows API used there does not support anything other than local accounts and ActiveDirectory accounts.
I've spent some time searching and I'm inclined to believe that AccountManagement also doesn't support anything other than local accounts and ActiveDirectory accounts too. See also https://github.com/dotnet/runtime/issues/30408

Since this module is not designed to manage accounts other than local accounts, the only thing we are trying to get the name of the external account for is to inform the user. If the API doesn't allow this, then we can only display the SID. I think we can change the code to just ignore this error.

**Comment by zenchicken** [comment]
@iSazonov I see the logic of your approach. I think that would be fine for our use cases. I would extend a suggestion that this aspect of the design decision be exposed in README to clarify your intent here for other module users/consumers.

Thanks for your help!

**Comment by iSazonov** [comment]
> When testing another group (Users), the command fails in the same way on the Windows 365 Desktop and on the original local desktop.

@zenchicken Could you please share follow information from the desktops:
```powershell
[System.Net.NetworkInformation.IPGlobalProperties]::GetIPGlobalProperties()
```

**Comment by zenchicken** [comment]
```
$> [System.Net.NetworkInformation.IPGlobalProperties]::GetIPGlobalProperties()
HostName      : CPC-jsh-15X3-JL
DomainName    :
NodeType      : Hybrid
DhcpScopeName :
IsWinsProxy   : False
```

**Comment by iSazonov** [comment]
I played with AccountManagement API and it doesn't seem to work as we would like - it is not show foreign accounts.
You can try follow script to make sure of this.
```powershell
$Name = "Administrators"
$groupPrincipalContext = [System.DirectoryServices.AccountManagement.PrincipalContext]::new([System.DirectoryServices.AccountManagement.ContextType]::Machine)
$groupPrincipal = [System.DirectoryServices.AccountManagement.GroupPrincipal]::FindByIdentity($groupPrincipalContext, $Name)
$groupPrincipal.GetMembers()

$groupPrincipal.Dispose()
$groupPrincipalContext.Dispose()
```

**Comment by zenchicken** [comment]
@iSazonov Curious, the Windows 365 and my local workstation did. Here was the output for the W365 case, redacted for private info:
```
 $groupPrincipal.GetMembers()

GivenName                         :
MiddleName                        :
Surname                           :
EmailAddress                      :
VoiceTelephoneNumber              :
EmployeeId                        :
AdvancedSearchFilter              : System.DirectoryServices.AccountManagement.AdvancedFilters
Enabled                           : True
AccountLockoutTime                :
LastLogon                         : 5/10/2022 5:52:33 AM
PermittedWorkstations             : {}
PermittedLogonTimes               : {255, 255, 255, 255…}
AccountExpirationDate             :
SmartcardLogonRequired            : False
DelegationPermitted               : True
BadLogonCount                     : 0
HomeDirectory                     :
HomeDrive                         :
ScriptPath                        :
LastPasswordSet                   : 7/23/2024 2:37:12 PM
LastBadPasswordAttempt            :
PasswordNotRequired               : False
PasswordNeverExpires              : True
UserCannotChangePassword          : False
AllowReversiblePasswordEncryption : False
Certificates                      : {}
Context                           : System.DirectoryServices.AccountManagement.PrincipalContext
ContextType                       : Machine
Description                       : Built-in account for administering the computer/domain
DisplayName                       :
SamAccountName                    : BuiltInAdmin
UserPrincipalName                 :
Sid                               : S-1-5-21-4037*****-500
Guid                              :
DistinguishedName                 :
StructuralObjectClass             :
Name                              : BuiltInAdmin

IsSecurityGroup       : True
GroupScope            : Local
Members               : {}
Context               : System.DirectoryServices.AccountManagement.PrincipalContext
ContextType           : Machine
Description           :
DisplayName           :
SamAccountName        :
UserPrincipalName     :
Sid                   : S-1-12-1-*******6064
Guid                  :
DistinguishedName     :
StructuralObjectClass :
Name                  :

IsSecurityGroup       : True
GroupScope            : Local
Members               : {}
Context               : System.DirectoryServices.AccountManagement.PrincipalContext
ContextType           : Machine
Description           :
DisplayName           :
SamAccountName        :
UserPrincipalName     :
Sid                   : S-1-12-1-*******0841
Guid                  :
DistinguishedName     :
StructuralObjectClass :
Name                  :

## NOTE: next entry is AzureAD prinicpal ##

IsSecurityGroup       : True
GroupScope            : Local
Members               : {}
Context               : System.DirectoryServices.AccountManagement.PrincipalContext
ContextType           : Machine
Description           :
DisplayName           : AzureAD\J*********
SamAccountName        : J******
UserPrincipalName     :
Sid                   : S-1-12-1-******6182
Guid                  :
DistinguishedName     :
StructuralObjectClass :
Name                  : J********
```

**Comment by iSazonov** [comment]
@zenchicken Thanks for good news! I'll add new commit tomorrow. 
Do you use the module from the [LocalAccounts-MS](https://github.com/iSazonov/LocalAccounts-MS) repository or from PowerShellGallery (published from [LocalAccounts](https://github.com/iSazonov/LocalAccounts))?

**Comment by zenchicken** [comment]
PowerShellGallery via `LocalAccounts`

**Comment by iSazonov** [comment]
Then I'll publish beta2 on PowerShellGallery in day.

**Comment by iSazonov** [comment]
Beta2 has been published.

**Comment by zenchicken** [comment]
@iSazonov great, works on both my affected systems. Thank you so much for quick turnaround!

**Comment by iSazonov** [comment]
@zenchicken Thanks for your investigations!
Notice, for opening issues in future please use https://github.com/iSazonov/LocalAccounts repository.
